REVOKE EXECUTE ON FUNCTION public.notify(uuid,text,text,text,text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.log_issue_created() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.log_request_created() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.on_comment_notify() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.on_issue_status_notify() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.on_request_status_notify() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.on_suggestion_response_notify() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_staff(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_staff(uuid) TO anon, authenticated;

INSERT INTO public.services (slug, name, summary, description, requirements, fee_info, processing_info, where_to_apply, where_to_claim, contact_info, source_note, sort_order) VALUES
('barangay-clearance','Barangay Clearance','A certification that a resident has no pending barangay case or derogatory record, commonly required for employment, permits and other transactions.','Barangay clearance is issued by the barangay under the Local Government Code of 1991 (RA 7160). Exact supporting documents may vary — confirm with the barangay hall before visiting.', ARRAY['Valid government-issued ID','Proof of residency in Barangay Balibago'], NULL, NULL, 'Barangay Balibago Hall, T. Aguas St., Balibago, Angeles City, Pampanga 2009', 'Barangay Balibago Hall', '(045) 624-5800', 'Service mandated under the Local Government Code of 1991 (RA 7160). Fees and processing times are not publicly published and are shown only once verified with the barangay.', 1),
('certificate-of-indigency','Certificate of Indigency','A certification that a resident belongs to a low-income household, often required for medical, educational or legal assistance.','Issued by the barangay to residents seeking assistance from government agencies. Requirements may vary — confirm with the barangay hall.', ARRAY['Valid government-issued ID','Proof of residency in Barangay Balibago'], NULL, NULL, 'Barangay Balibago Hall, T. Aguas St., Balibago, Angeles City, Pampanga 2009', 'Barangay Balibago Hall', '(045) 624-5800', 'Commonly issued by Philippine barangays. Fees and processing times are not publicly published and are shown only once verified with the barangay.', 2),
('certificate-of-residency','Certificate of Residency','A certification confirming that a person resides within Barangay Balibago.','Issued by the barangay for residents who need documentary proof of residence. Requirements may vary — confirm with the barangay hall.', ARRAY['Valid government-issued ID','Proof of residency in Barangay Balibago'], NULL, NULL, 'Barangay Balibago Hall, T. Aguas St., Balibago, Angeles City, Pampanga 2009', 'Barangay Balibago Hall', '(045) 624-5800', 'Commonly issued by Philippine barangays. Fees and processing times are not publicly published and are shown only once verified with the barangay.', 3),
('barangay-business-clearance','Barangay Business Clearance','Barangay-level clearance required before applying for a city business permit for a business located in Barangay Balibago.','Under Section 152 of the Local Government Code, barangays may issue clearance for any business or activity located in the barangay before a city or municipal permit is issued.', ARRAY['Valid government-issued ID of the owner or authorized representative','Business name and exact business address within Barangay Balibago'], NULL, NULL, 'Barangay Balibago Hall, T. Aguas St., Balibago, Angeles City, Pampanga 2009', 'Barangay Balibago Hall', '(045) 624-5800', 'Basis: Section 152, Local Government Code of 1991 (RA 7160). Fee schedules are set by barangay ordinance and are shown only once verified.', 4),
('katarungang-pambarangay','Katarungang Pambarangay (Barangay Mediation)','Community dispute settlement and mediation handled by the Lupong Tagapamayapa of the barangay.','Under the Katarungang Pambarangay system, certain disputes between residents of the same city or municipality must first be brought to the barangay for mediation and conciliation before they can be filed in court.', ARRAY['Valid government-issued ID','Details of the complaint and the parties involved'], NULL, NULL, 'Barangay Balibago Hall, T. Aguas St., Balibago, Angeles City, Pampanga 2009', 'Barangay Balibago Hall', '(045) 624-5800', 'Basis: Chapter 7, Local Government Code of 1991 (RA 7160). Schedules and any applicable fees are shown only once verified with the barangay.', 5);