/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MapRouteImport } from './routes/map'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityPostIdRouteImport } from './routes/community/$postId'
import { Route as CommunityUpdatesRouteImport } from './routes/community/updates'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues/$issueId'
import { Route as IssuesNewRouteImport } from './routes/issues/new'
import { Route as CommunitySuggestionsIndexRouteImport } from './routes/community/suggestions/index'
import { Route as CommunitySuggestionsSuggestionIdRouteImport } from './routes/community/suggestions/$suggestionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/community/$postId',
  path: '/community/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityUpdatesRoute = CommunityUpdatesRouteImport.update({
  id: '/community/updates',
  path: '/community/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesNewRoute = IssuesNewRouteImport.update({
  id: '/issues/new',
  path: '/issues/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySuggestionsIndexRoute =
  CommunitySuggestionsIndexRouteImport.update({
    id: '/community/suggestions/',
    path: '/community/suggestions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunitySuggestionsSuggestionIdRoute =
  CommunitySuggestionsSuggestionIdRouteImport.update({
    id: '/community/suggestions/$suggestionId',
    path: '/community/suggestions/$suggestionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/updates': typeof CommunityUpdatesRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/issues/new': typeof IssuesNewRoute
  '/community/': typeof CommunityIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/community/suggestions/$suggestionId': typeof CommunitySuggestionsSuggestionIdRoute
  '/community/suggestions/': typeof CommunitySuggestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/updates': typeof CommunityUpdatesRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/issues/new': typeof IssuesNewRoute
  '/community': typeof CommunityIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/community/suggestions/$suggestionId': typeof CommunitySuggestionsSuggestionIdRoute
  '/community/suggestions': typeof CommunitySuggestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/updates': typeof CommunityUpdatesRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/issues/new': typeof IssuesNewRoute
  '/community/': typeof CommunityIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/community/suggestions/$suggestionId': typeof CommunitySuggestionsSuggestionIdRoute
  '/community/suggestions/': typeof CommunitySuggestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/services'
    | '/sitemap.xml'
    | '/community/$postId'
    | '/community/updates'
    | '/issues/$issueId'
    | '/issues/new'
    | '/community/'
    | '/issues/'
    | '/community/suggestions/$suggestionId'
    | '/community/suggestions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/services'
    | '/sitemap.xml'
    | '/community/$postId'
    | '/community/updates'
    | '/issues/$issueId'
    | '/issues/new'
    | '/community'
    | '/issues'
    | '/community/suggestions/$suggestionId'
    | '/community/suggestions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/services'
    | '/sitemap.xml'
    | '/community/$postId'
    | '/community/updates'
    | '/issues/$issueId'
    | '/issues/new'
    | '/community/'
    | '/issues/'
    | '/community/suggestions/$suggestionId'
    | '/community/suggestions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MapRoute: typeof MapRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  CommunityUpdatesRoute: typeof CommunityUpdatesRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  IssuesNewRoute: typeof IssuesNewRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  CommunitySuggestionsSuggestionIdRoute: typeof CommunitySuggestionsSuggestionIdRoute
  CommunitySuggestionsIndexRoute: typeof CommunitySuggestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/community/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/updates': {
      id: '/community/updates'
      path: '/community/updates'
      fullPath: '/community/updates'
      preLoaderRoute: typeof CommunityUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/new': {
      id: '/issues/new'
      path: '/issues/new'
      fullPath: '/issues/new'
      preLoaderRoute: typeof IssuesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/suggestions/': {
      id: '/community/suggestions/'
      path: '/community/suggestions'
      fullPath: '/community/suggestions/'
      preLoaderRoute: typeof CommunitySuggestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/suggestions/$suggestionId': {
      id: '/community/suggestions/$suggestionId'
      path: '/community/suggestions/$suggestionId'
      fullPath: '/community/suggestions/$suggestionId'
      preLoaderRoute: typeof CommunitySuggestionsSuggestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MapRoute: MapRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CommunityPostIdRoute: CommunityPostIdRoute,
  CommunityUpdatesRoute: CommunityUpdatesRoute,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  IssuesNewRoute: IssuesNewRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  CommunitySuggestionsSuggestionIdRoute: CommunitySuggestionsSuggestionIdRoute,
  CommunitySuggestionsIndexRoute: CommunitySuggestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
