/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ReportRouteImport } from './routes/report'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as DashboardAuditLogRouteImport } from './routes/dashboard/audit-log'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard/community'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard/documents'
import { Route as DashboardIssuesRouteImport } from './routes/dashboard/issues'
import { Route as DashboardMapRouteImport } from './routes/dashboard/map'
import { Route as DashboardOfficialsRouteImport } from './routes/dashboard/officials'
import { Route as DashboardPuroksRouteImport } from './routes/dashboard/puroks'
import { Route as DashboardResidentsRouteImport } from './routes/dashboard/residents'
import { Route as DashboardSchedulesRouteImport } from './routes/dashboard/schedules'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardSlaRouteImport } from './routes/dashboard/sla'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuditLogRoute = DashboardAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardIssuesRoute = DashboardIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOfficialsRoute = DashboardOfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPuroksRoute = DashboardPuroksRouteImport.update({
  id: '/puroks',
  path: '/puroks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResidentsRoute = DashboardResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulesRoute = DashboardSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSlaRoute = DashboardSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/issues': typeof DashboardIssuesRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/officials': typeof DashboardOfficialsRoute
  '/dashboard/puroks': typeof DashboardPuroksRoute
  '/dashboard/residents': typeof DashboardResidentsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/sla': typeof DashboardSlaRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/issues': typeof DashboardIssuesRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/officials': typeof DashboardOfficialsRoute
  '/dashboard/puroks': typeof DashboardPuroksRoute
  '/dashboard/residents': typeof DashboardResidentsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/sla': typeof DashboardSlaRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/issues': typeof DashboardIssuesRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/officials': typeof DashboardOfficialsRoute
  '/dashboard/puroks': typeof DashboardPuroksRoute
  '/dashboard/residents': typeof DashboardResidentsRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/sla': typeof DashboardSlaRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/report'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/audit-log'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/issues'
    | '/dashboard/map'
    | '/dashboard/officials'
    | '/dashboard/puroks'
    | '/dashboard/residents'
    | '/dashboard/schedules'
    | '/dashboard/services'
    | '/dashboard/sla'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/audit-log'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/issues'
    | '/dashboard/map'
    | '/dashboard/officials'
    | '/dashboard/puroks'
    | '/dashboard/residents'
    | '/dashboard/schedules'
    | '/dashboard/services'
    | '/dashboard/sla'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/report'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/audit-log'
    | '/dashboard/community'
    | '/dashboard/documents'
    | '/dashboard/issues'
    | '/dashboard/map'
    | '/dashboard/officials'
    | '/dashboard/puroks'
    | '/dashboard/residents'
    | '/dashboard/schedules'
    | '/dashboard/services'
    | '/dashboard/sla'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/audit-log': {
      id: '/dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/audit-log'
      preLoaderRoute: typeof DashboardAuditLogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/issues': {
      id: '/dashboard/issues'
      path: '/issues'
      fullPath: '/dashboard/issues'
      preLoaderRoute: typeof DashboardIssuesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/officials': {
      id: '/dashboard/officials'
      path: '/officials'
      fullPath: '/dashboard/officials'
      preLoaderRoute: typeof DashboardOfficialsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/puroks': {
      id: '/dashboard/puroks'
      path: '/puroks'
      fullPath: '/dashboard/puroks'
      preLoaderRoute: typeof DashboardPuroksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/residents': {
      id: '/dashboard/residents'
      path: '/residents'
      fullPath: '/dashboard/residents'
      preLoaderRoute: typeof DashboardResidentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sla': {
      id: '/dashboard/sla'
      path: '/sla'
      fullPath: '/dashboard/sla'
      preLoaderRoute: typeof DashboardSlaRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardAuditLogRoute: typeof DashboardAuditLogRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardIssuesRoute: typeof DashboardIssuesRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardOfficialsRoute: typeof DashboardOfficialsRoute
  DashboardPuroksRoute: typeof DashboardPuroksRoute
  DashboardResidentsRoute: typeof DashboardResidentsRoute
  DashboardSchedulesRoute: typeof DashboardSchedulesRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSlaRoute: typeof DashboardSlaRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardAuditLogRoute: DashboardAuditLogRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardIssuesRoute: DashboardIssuesRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardOfficialsRoute: DashboardOfficialsRoute,
  DashboardPuroksRoute: DashboardPuroksRoute,
  DashboardResidentsRoute: DashboardResidentsRoute,
  DashboardSchedulesRoute: DashboardSchedulesRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSlaRoute: DashboardSlaRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
